# Generated by Django 4.2.1 on 2023-05-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(default='Chapter name', max_length=50)),
                ('chapter_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DuoMathCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='Course name', max_length=100)),
                ('type_of_school', models.CharField(choices=[('PS', 'Primary School'), ('SS', 'Secondary School')], default='PS', max_length=2)),
                ('type_of_level', models.CharField(choices=[('B', 'Basic'), ('A', 'Advance')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_topic', models.CharField(default='Lesson topic', max_length=50)),
                ('lesson_number', models.PositiveIntegerField(default=0)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_number', models.PositiveIntegerField(default=0)),
                ('function_name', models.CharField(default='PPPCH00L00E00', max_length=13)),
                ('difficult', models.CharField(choices=[('E', 'Easy'), ('M', 'Mid'), ('H', 'Hard')], default='E', max_length=1)),
                ('text', models.CharField(default='Text', max_length=300)),
                ('answear', models.CharField(default='Answear', max_length=300)),
                ('points', models.PositiveIntegerField(default=1)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.duomathcourse'),
        ),
    ]
